# Generated by Django 3.0.3 on 2022-09-12 22:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_index=True, default='Inactive', max_length=50, verbose_name='Status')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('like_count', models.IntegerField(default=0, verbose_name='Like Count')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('category', models.CharField(choices=[('Hot', 'HOT'), ('Cold', 'COLD'), ('Bagel', 'BAGEL'), ('All', 'ALL')], default='ALL', max_length=50, verbose_name='Category')),
                ('description', models.CharField(max_length=10000, verbose_name='description')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated Datetime')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
