# Generated by Django 3.0.3 on 2022-09-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20220912_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, default='Item Description', max_length=10000, verbose_name='description'),
        ),
    ]
